
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'calibviz_pipeline'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'calibviz_pipeline'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-end: 
  - "CHECKPOINT;"
  - "VACUUM;"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  calibviz_pipeline:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: table
      +schema: staging
      +tags: ['staging']
    metrics:
      +materialized: table
      +schema: metrics
      +tags: ['metrics']
    intermediate:
      +materialized: table
      +schema: intermediate
      +tags: ['intermediate']
seeds:
  calibviz_pipeline:
      +schema: seeds

vars:
  scenarios: 
  - "2022_S0_v2"
  - "2026_S1"
  base_path: "T:/STORAGE-63T/2025RP_draft/abm_runs_v2/"
  include_gq: false  # set to true to include GQ households, false to filter them out
  sample_rate: 1.0   # set to 1.0 for full sample, 0.1 for 10% sample, etc.